#!/usr/bin/env python3
"""
Dummy Task Watcher for AI_Employee_Vault
Simulates incoming tasks by creating files every 20 seconds
"""

import os
import sys
import logging
import time
import random
from pathlib import Path
from datetime import datetime


# Setup logging
def setup_logging():
    """Configure logging to file and console"""
    log_dir = Path(__file__).parent.parent / "Logs"
    log_dir.mkdir(exist_ok=True)

    log_file = log_dir / f"dummy_watcher_{datetime.now().strftime('%Y%m%d_%H%M%S')}.log"

    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
        handlers=[
            logging.FileHandler(log_file),
            logging.StreamHandler(sys.stdout)
        ]
    )

    logger = logging.getLogger(__name__)
    logger.info("=" * 80)
    logger.info("DUMMY TASK WATCHER STARTED")
    logger.info(f"Log file: {log_file}")
    logger.info("=" * 80)

    return logger


class DummyTaskGenerator:
    """Generate and save dummy tasks"""

    def __init__(self, logger, base_path):
        self.logger = logger
        self.base_path = base_path
        self.action_dir = base_path / "Needs_Action"
        self.action_dir.mkdir(exist_ok=True)
        self.task_counter = 0

        # Fake senders
        self.senders = [
            "alice@company.com",
            "bob@company.com",
            "charlie@company.com",
            "diana@company.com",
            "eve@company.com"
        ]

        # Fake task messages
        self.messages = [
            "Review and approve Q2 budget proposal",
            "Update team documentation with latest changes",
            "Schedule meetings for the upcoming sprint",
            "Analyze customer feedback from recent survey",
            "Prepare presentation slides for stakeholder meeting",
            "Debug issue reported in production environment",
            "Update dependencies in main repository",
            "Create user guide for new feature",
            "Organize code review session with team",
            "Plan team building activity for next month"
        ]

    def generate_task(self):
        """Create a new dummy task"""
        try:
            self.task_counter += 1

            # Select random sender and message
            sender = random.choice(self.senders)
            message = random.choice(self.messages)
            timestamp = datetime.now().isoformat()

            # Create task filename
            task_filename = f"TASK_dummy_{self.task_counter:03d}.md"
            task_file = self.action_dir / task_filename

            # Create task content
            task_content = f"""# Incoming Task #{self.task_counter}

**From:** {sender}
**Received:** {timestamp}
**Status:** New

## Task Description
{message}

## Details
- **Task ID:** dummy_{self.task_counter:03d}
- **Priority:** Normal
- **Action Required:** Review and process

---
*Generated by Dummy Task Watcher - Simulated incoming task*
"""

            # Write task file
            with open(task_file, 'w') as f:
                f.write(task_content)

            self.logger.info(f"📧 New task created: {task_filename}")
            self.logger.info(f"   From: {sender}")
            self.logger.info(f"   Message: {message}")

            # Create metadata file
            self._create_metadata(task_file, sender, timestamp)

        except Exception as e:
            self.logger.error(f"❌ Error generating task: {str(e)}", exc_info=True)

    def _create_metadata(self, task_file, sender, timestamp):
        """Create .md metadata file for the task"""
        try:
            metadata_filename = f"{task_file.stem}_metadata.md"
            metadata_file = task_file.parent / metadata_filename

            metadata_content = f"""# Task Metadata

**Task File:** `{task_file.name}`
**Metadata File:** `{metadata_filename}`

## Task Information
- **Sender:** {sender}
- **Received:** {timestamp}
- **Created:** {datetime.now().isoformat()}

## Status
- **Status:** Pending Review
- **Action Required:** Process from `Needs_Action/` folder

---
*Generated by Dummy Task Watcher*
"""

            with open(metadata_file, 'w') as f:
                f.write(metadata_content)

            self.logger.info(f"✅ Metadata created: {metadata_filename}")

        except Exception as e:
            self.logger.error(f"❌ Error creating metadata: {str(e)}", exc_info=True)


def main():
    """Main function to run the dummy task watcher"""
    # Get project base path
    base_path = Path(__file__).parent.parent

    # Setup logging
    logger = setup_logging()

    # Verify paths
    action_dir = base_path / "Needs_Action"
    if not action_dir.exists():
        action_dir.mkdir(parents=True, exist_ok=True)

    logger.info(f"Output directory: {action_dir}")
    logger.info("ℹ️  Task generator will create new tasks every 20 seconds")
    logger.info("=" * 80)

    # Create task generator
    task_generator = DummyTaskGenerator(logger, base_path)

    # Run forever, creating tasks every 20 seconds
    try:
        logger.info("Starting task generator...")
        logger.info("✅ Generator is running. Creating tasks every 20 seconds...")
        logger.info("=" * 80)

        while True:
            task_generator.generate_task()
            time.sleep(20)

    except KeyboardInterrupt:
        logger.info("\n⛔ Shutdown signal received (Ctrl+C)")

    finally:
        logger.info("Task generator shutdown complete")
        logger.info("=" * 80)


if __name__ == "__main__":
    main()
